project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"                    # solo renderiza los .qmd de la raíz
    - "!cursos/microeconomia_II/**"  # NO renderizar nada dentro del libro
    
lang: es
date-format: "D [de] MMMM [de] YYYY"

website:
  title: "Sebastián Cortés"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - text: Cursos
        menu:
          - href: cursos/microeconomia_II/   # apunta al libro ya compilado
            text: Teoría Microeconómica II
  page-footer:
    center: "© 2025 Sebastián Cortés"
  search:
    location: navbar
    type: overlay   # buscador en overlay (en español si lang=es)
    
format:
  html:
    lang: es              # atributo lang del HTML
    toc: true
    toc-title: "Tabla de contenidos"
    theme: cosmo
    css: styles.css
    code-copy: true       # botón “Copiar”
    link-external-newwindow: true

    
editor: visual