project:
  type: website
  output-dir: docs

website:
  title: "Sebastián Cortés"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Cursos
        menu: 
          - href: microeconomia_II.qmd
            text: Teoría Microeconómica II

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual

