project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"                    # solo renderiza los .qmd de la raíz
    - "!cursos/microeconomia_II/**"  # NO renderizar nada dentro del libro

website:
  title: "Sebastián Cortés"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Cursos
        menu:
          - href: cursos/microeconomia_II/   # apunta al libro ya compilado
            text: Teoría Microeconómica II

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

