project:
  type: website
  output-dir: ../../docs/cursos/microeconomia_II

lang: es
date-format: "D [de] MMMM [de] YYYY"

website:
  title: "Teoría Microeconómica II EC2200"
  # usa la navbar del sitio principal
  navbar:
    pinned: true
    left:
      - href: ../../          # ← vuelve al Home del sitio (docs/)
        text: Inicio            # o "Inicio", como prefieras
      - text: Cursos
        menu:
          - href: ../../cursos/microeconomia_II/
            text: Teoría Microeconómica II
  page-footer:
    center: "© 2025 Sebastián Cortés"
  sidebar:
    style: floating
    search: true
    contents:
      - text: "Primer parcial"
        href: index.qmd
      - text: "Segundo parcial"
        href: segundo_parcial.qmd
      - text: "Tercer parcial"
        href: tercer_parcial.qmd
      - text: "Material del curso"
        href: material_apoyo.qmd
      - text: "Referencias"
        href: references.qmd

bibliography: references.bib


format:
  html:
    lang: es
    theme: cosmo
    toc: true
    toc-title: "Tabla de contenidos"
    number-sections: false
  pdf:
    toc: true
    toc-depth: 3
    toc-title: "Tabla de contenidos"
    lot: true
    lof: true