---
title: "Referencias"
format: html
nocite: |
  @*
reference-section-title: "" 
bibliography: references.bib
---

::: {#refs}
:::

---


> **Aviso**\
> El presente documento se basa en el curso de Teoría Microeconómica II, impartido por el profesor Edgar Robles y el asistente Sebastián Fernández. Gran parte del contenido corresponde a una reproducción literal de los apuntes elaborados tanto por el profesor como por el asistente durante las clases, así como a material compartido en dicho curso. Una parte menor proviene de apuntes propios y explicaciones personales.
>
> **Usted es libre de:**\
> - Compartir — copiar y redistribuir el material en cualquier medio o formato.\
> La licenciante no puede revocar estas libertades en tanto usted siga los términos de la licencia.
>
> **Bajo los siguientes términos:**\
> - **Atribución** — Usted debe dar crédito de manera adecuada, brindar un enlace a la licencia, e indicar si se han realizado cambios. Puede hacerlo en cualquier forma razonable, pero no de forma tal que sugiera que usted o su uso tienen el apoyo de la licenciante.\
> - **No Comercial** — Usted no puede hacer uso del material con propósitos comerciales.\
> - **Sin Derivadas** — Si remezcla, transforma o crea a partir del material, no podrá distribuir el material modificado.
>
> **No hay restricciones adicionales** — No puede aplicar términos legales ni medidas tecnológicas que restrinjan legalmente a otros a hacer cualquier uso permitido por la licencia.
